export const stateNums: { [key: string]: number } = {
  "al": 1,
  "ak": 2,
  "ar": 5,
  "az": 4,
  "ca": 6,
  "co": 8,
  "ct": 9,
  "dc": 11,
  "de": 10,
  "fl": 12,
  "ga": 13,
  "hi": 15,
  "ia": 19,
  "id": 16,
  "il": 17,
  "in": 18,
  "ks": 20,
  "ky": 21,
  "la": 22,
  "ma": 25,
  "md": 24,
  "me": 23,
  "mi": 26,
  "mn": 27,
  "mo": 29,
  "ms": 28,
  "mt": 30,
  "nc": 37,
  "nd": 38,
  "ne": 31,
  "nh": 33,
  "nj": 34,
  "nm": 35,
  "nv": 32,
  "ny": 36,
  "oh": 39,
  "ok": 40,
  "or": 41,
  "pa": 42,
  "ri": 44,
  "sc": 45,
  "sd": 46,
  "tn": 47,
  "tx": 48,
  "ut": 49,
  "va": 51,
  "vt": 50,
  "wa": 53,
  "wi": 55,
  "wv": 54,
  "wy": 56
};

export const stateNames: { [key: string]: string } = {
  "ak": "Alaska",
  "al": "Alabama",
  "ar": "Arkansas",
  "az": "Arizona",
  "ca": "California",
  "co": "Colorado",
  "ct": "Conneticut",
  "dc": "District of Columbia",
  "de": "Delaware",
  "fl": "Florida",
  "ga": "Georgia",
  "hi": "Hawaii",
  "ia": "Iowa",
  "id": "Idaho",
  "il": "Illinois",
  "in": "Indiana",
  "ks": "Kansas",
  "ky": "Kentucky",
  "la": "Louisiana",
  "ma": "Massachusetts",
  "md": "Maryland",
  "me": "Maine",
  "mi": "Michigan",
  "mn": "Minnesota",
  "mo": "Missouri",
  "ms": "Mississipi",
  "mt": "Montana",
  "nc": "North Carolina",
  "nd": "North Dakota",
  "ne": "Nebraska",
  "nh": "New Hampshire",
  "nj": "New Jersey",
  "nm": "New Mexico",
  "nv": "Nevada",
  "ny": "New York",
  "oh": "Ohio",
  "ok": "Oklahoma",
  "or": "Oregon",
  "pa": "Pensylvania",
  "ri": "Rhode Island",
  "sc": "South Carolina",
  "sd": "South Dakota",
  "tn": "Tennesee",
  "tx": "Texas",
  "ut": "Utah",
  "va": "Virginia",
  "vt": "Vermont",
  "wa": "Washington",
  "wi": "Wisconsin",
  "wv": "West Virginia",
  "wy": "Wyoming",
};

export const reverseNames = {
  "Alaska": "ak",
  "Alabama": "al",
  "Arkansas": "ar",
  "Arizona": "az",
  "California": "ca",
  "Colorado": "co",
  "Conneticut": "ct",
  "District of Columbia": "dc",
  "Delaware": "dc",
  "Florida": "fl",
  "Georgia": "ga",
  "Hawaii": "hi",
  "Iowa": "ia",
  "Idaho": "id",
  "Illinois": "il",
  "Indiana": "in",
  "Kansas": "ks",
  "Kentucky": "ky",
  "Louisiana": "la",
  "Massachusetts": "ma",
  "Maryland": "md",
  "Maine": "me",
  "Michigan": "mi",
  "Minnesota": "mn",
  "Missouri": "mo",
  "Mississipi": "ms",
  "Montana": "mt",
  "North Carolina": "nc",
  "North Dakota": "nd",
  "Nebraska": "ne",
  "New Hampshire": "nh",
  "New Jersey": "nj",
  "New Mexico": "m",
  "Nevada": "nv",
  "New York": "ny",
  "Ohio": "oh",
  "Oklahoma": "ok",
  "Oregon": "or",
  "Pensylvania": "pa",
  "Rhode Island": "ri",
  "South Carolina": "sc",
  "South Dakota": "sd",
  "Tennesee": "tn",
  "Texas": "tx",
  "Utah": "ut",
  "Virginia": "va",
  "Vermont": "vt",
  "Washington": "wa",
  "Wisconsin": "wi",
  "West Virginia": "wv",
  "Wyoming": "wy"
};
